### ISSUE TITLE
Android gradle sync failed 

### ISSUE THREAD

**Issue by AmirNexter** [Survicate/react-native-survicate#15] opened 2022-03-15 10:44 UTC
after upgrade to 1.1.5 we are getting the following error: 

build file 'node_modules/@survicate/react-native-survicate/android/build.gradle': 38: only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed

After fixing that I get a new error:

Build file 'node_modules/@survicate/react-native-survicate/android/build.gradle' line: 154
> Could not find method mavenDeployer() for arguments [build_by5hivzmvuokv3yw57k3h58gs$_run_closure4$_closure16$_closure18@3ccca97a] on repository container of type org.gradle.api.internal.artifacts.dsl.DefaultRepositoryHandler.

**Comment by sergey-duzhych** [comment] 2022-03-15 14:26
Hi @AmirNexter, thanks for reporting this! I will let you know as soon as the issue is fixed.

**Comment by wenge8n** [comment] 2022-03-23 10:42
Hi @sergey-duzhych any update on this?

**Comment by sergey-duzhych** [comment] 2022-03-23 11:03
Hi @wenge8n, we are still working on it. I will let you know once the issue is resolved.

**Comment by wenge8n** [comment] 2022-03-23 13:09
Thanks

**Comment by sergey-duzhych** [comment] 2022-03-25 12:45
Hi @AmirNexter @wenge8n The issue has been fixed in the latest version of React Native SDK 1.1.6.

**Comment by wenge8n** [comment] 2022-03-25 13:45
Thanks @sergey-duzhych. I tested 1.1.6 and the error has gone.

**Comment by kamilk-survicate** [comment] 2022-03-25 13:59
Fixed in version 1.1.6

**Closed** 2022-03-25 13:58 UTC

**Comment by wenge8n** [comment] 2022-05-16 16:58
In react native 0.68.2, the gradle sync fails again.

Caused by: org.gradle.api.artifacts.UnknownConfigurationException: Configuration with name 'compile' not found.

![image](https://user-images.githubusercontent.com/36442590/168644830-d01563d0-e6db-4234-95f0-b1cbb95a20b5.png)

How to resolve this?
