### ISSUE TITLE
Plugin with id 'maven' not found

### ISSUE THREAD

**Issue by adblanc** [Survicate/react-native-survicate#13] opened 2022-02-04 10:31 UTC
Hi, maven plugin has been deprecated in gradle 7 as seen [here](https://github.com/expo/expo/issues/12774#issuecomment-832073020)
As a result,  android build fails on react native >= 0.67

```
* Where:
1: Task failed with an exception.
-----------
* Where:
Build file '/node_modules/@survicate/react-native-survicate/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':survicate_react-native-survicate'.
> Plugin with id 'maven' not found.
```

**Comment by adrianso** [comment] 2022-02-17 03:13
Any updates?

**Comment by madeinnz** [comment] 2022-02-18 04:24
having the same issue. Can I get an eta on a fix for this please?

**Comment by kamilk-survicate** [comment] 2022-02-18 09:09
@adblanc @adrianso @madeinnz Fix for the issue is under development, I expect to have it ready in the few days. I will update the status.

**Comment by jartmez** [comment] 2022-02-22 21:32
@kamilk-survicate maybe this PR from the react-native-reanimated project could help with this migration to Gradle 7 https://github.com/software-mansion/react-native-reanimated/pull/2881/files

**Comment by madeinnz** [comment] 2022-03-08 21:33
@kamilk-survicate  over a month now? whats happening with this? is it going to be fixed? or do I stop using survicate?

**Comment by kamilk-survicate** [comment] 2022-03-09 08:22
The issue was addressed in version 1.1.5 - please check. 
Sorry for lack of info earlier.

**Comment by madeinnz** [comment] 2022-03-10 23:42
Hi @kamilk-survicate 
unfortunately with version 1.1.5 I get the following errors when trying to build:


FAILURE: Build failed with an exception.

* Where:
Build file '/Users/markandrews/Documents/Development/nw-clubcard-app/node_modules/@survicate/react-native-survicate/android/build.gradle' line: 38

* What went wrong:
Could not compile build file '/Users/markandrews/Documents/Development/nw-clubcard-app/node_modules/@survicate/react-native-survicate/android/build.gradle'.
> startup failed:
  build file '/Users/markandrews/Documents/Development/nw-clubcard-app/node_modules/@survicate/react-native-survicate/android/build.gradle': 38: only buildscript {} and other plugins {} script blocks are allowed before plugins {} blocks, no other statements are allowed
  
  See https://docs.gradle.org/7.2/userguide/plugins.html#sec:plugins_block for information on the plugins {} block
  
   @ line 38, column 1.
     plugins {
     ^
  
  1 error

**Comment by madeinnz** [comment] 2022-03-10 23:45
has anyone else tried version 1.1.5?
if so what were the results that you encountered please?

**Comment by kamilk-survicate** [comment] 2022-03-11 18:43
@madeinnz I was testing it in my sample application and didn't notice any problems, however I'll check the `build.gradle` file and get back to U on Monday.

**Comment by sergey-duzhych** [comment] 2022-03-25 12:49
The issue has been fixed in the latest version of React Native SDK 1.1.6.

**Closed** 2022-03-28 15:52 UTC
